### PR TITLE
Move @types into devDependencies

### PR DESCRIPTION
**Pull request by orta**
# What Changed

I moved the dependencies for al the TS types into the dev section, this is so that consumer don't need to have them included. You may have thought about this already, and have a reasoning for it - and if so, I'm happy to close this

# Why

Less dependencies for consumers

### CODE REVIEW

**Comment by hipstersmoothie** [comment]
@adierkens we probably only need the types as deps if #84 is really a goal

**Comment by adierkens** [comment]
True, and we'd only want the types that _could_ appear from calling public API methods, not necessarily _all_ of them.

**Comment by hipstersmoothie** [comment]
Given @adierkens's last comment it seems like none of the types would be accessible via the public API so think this is good to merge.

**Comment by orta** [comment]
All makes sense to me, thanks folks

**Pull request merged**
